### ISSUE TITLE
createMiddlewareSupabaseClient does not return the Session in Next.js middleware.

### ISSUE THREAD

**Issue by jmcannon** [supabase/auth-helpers#497] opened 2023-04-09 04:21 UTC
This boilerplate code does not currently work: https://supabase.com/docs/guides/auth/auth-helpers/nextjs#auth-with-nextjs-middleware, with `createMiddlewareSupabaseClient` writing this error to terminal:

`Failed to parse cookie string: [Error: The edge runtime does not support Node.js 'buffer' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime]`

In my project, which is currently using the most basic boilerplate from the docs and Auth UI, I can confirm that the session is being created on login, stored in a cookie, and accessible by other means such as `useUser`.

**Comment by ihti** [comment] 2023-04-09 10:11
Same here. Suddenly my Next.js app at Vercel started falling on auth. 

It seems like the issue is here: https://github.com/supabase/auth-helpers/commit/1ea258efbfcd0501c7528b2d95749b62d0fdf12f#diff-ab917dde7a6f132319af890fd890465d092c2787251a43b45088392a313b9608

**Comment by mryechkin** [comment] 2023-04-09 12:26
I'm experiencing this as well. Worked fine up until 0.5.8

**Comment by K1ssSh0t** [comment] 2023-04-10 22:31
I have the same problem

**Comment by KajSzy** [comment] 2023-04-11 19:19
This blocks me from upgrading to next 13.3, which brings A LOT for app router

**Comment by Garett-MacGowan** [comment] 2023-04-11 21:15
+1

**Comment by f-o-w-l** [comment] 2023-04-11 22:04
+1 help out the NextJS gang

**Comment by KajSzy** [comment] 2023-04-12 07:52
> +1 Confirmed that it breaks at 0.5.9. Using 0.5.8 as @mryechkin suggested until it is fixed.

0.5.8 doesn't work with next 13.3

**Comment by nico-bachner** [comment] 2023-04-13 21:13
> Same here. Suddenly my Next.js app at Vercel started falling on auth.
> 
> It seems like the issue is here: [1ea258e#diff-ab917dde7a6f132319af890fd890465d092c2787251a43b45088392a313b9608](https://github.com/supabase/auth-helpers/commit/1ea258efbfcd0501c7528b2d95749b62d0fdf12f#diff-ab917dde7a6f132319af890fd890465d092c2787251a43b45088392a313b9608)

You seem to be on the money with this one. The library relies on Buffer:

```ts
return Buffer.from(bin, 'binary').toString('base64');
```

Buffer is not explicitly imported in the library's source, which may have caused the confusion.

https://nodejs.dev/en/api/v19/buffer/

**Comment by AlaaMX** [comment] 2023-04-14 13:25
its working on next 13.2.4 and auth-helpers-nextjs 0.5.8

**Comment by silentworks** [comment] 2023-04-14 15:20
@nico-bachner the dependency we are using has `Buffer` in it, but if the server you are using doesn't support Buffer it falls back to its own implementation. I reached out to the Vercel team about this and they mentioned to me that Vercel Edge Runtime now supports `Buffer` and the latest NextJS works fine with buffer. However upon my test with a new NextJS project while doing the build step I get warnings about `Buffer` being used in the dependency we are using, these warnings are to do with not even the use of `Buffer` but to check if `Buffer` is available in the first place. I created a test repo showing the warnings and asked the Vercel team to look into it but I haven't heard back from them as yet.

https://vercel.com/changelog/improved-node-js-compatibility-for-edge-middleware-and-edge-functions

![image](https://user-images.githubusercontent.com/79497/232084921-35fa1dc8-6e03-4e67-82eb-0f543976c0b0.png)

**Comment by nico-bachner** [comment] 2023-04-14 21:51
@silentworks Interesting. Thanks a bunch for the explanation.

**Comment by silentworks** [comment] 2023-04-15 13:41
I'm looking into using `jose` as a dependency instead of `js-base64`. My initial tests shows there are no warnings when trying to run the build, but I need to do more test to make sure that the correct values are being returned from the token and to also make sure that the issue from #487 doesn't return with this change. I will keep everyone updated on this thread if all tests go well and when a new release goes out. I'm still waiting to hear from the Vercel team but this will be a more immediate fix I think.

**Comment by bramarcade** [comment] 2023-04-15 19:42
@silentworks confirming the error went away for me with Next 13.3 and auth-helpers-nextjs at 0.5.9

**Comment by silentworks** [comment] 2023-04-15 20:08
@bramarcade yeah that's because we removed buffer and used a custom implementation at that time but that had a knock on effect and cause issues #487.

**Comment by silentworks** [comment] 2023-04-16 17:10
Can someone in this thread facing this issue please try with the latest canary release of NextJS. It would seem like they fixed the buffer issue in this version. I just tested it with version `13.3.1-canary.8` of `next`. Please report back if the issue has been resolved when using this version.

**Comment by nico-bachner** [comment] 2023-04-17 10:03
@silentworks I've tried with `13.3.1-canary.8`, but the issue still seems to be present. 
The session returned by `getSession()` from `createMiddlewareSupabaseClient()` is null, whereas on the client side, the correct session object is shown.

**Comment by silentworks** [comment] 2023-04-17 10:39
@nico-bachner the issue I'm referring to here is `buffer` showing up as an error or warning.

**Comment by juanivrs** [comment] 2023-04-17 11:12
I´ve managed to make it work using

 `
"@supabase/auth-helpers-nextjs": "^0.6.0",
"@supabase/auth-helpers-react": "^0.3.1",
"@supabase/supabase-js": "^2.15.0",
"next": "^13.3.0",
`

Remember that next 13.3.0 has a problem (fail to parse json) that you can fix by changing the export default function to const and then exporting it below

**Comment by Venipa** [comment] 2023-04-17 12:35
i've updated to the latest canary versions, now its unable to parse the cookies
```
Failed to parse cookie string: [SyntaxError: Unexpected token , in JSON at position 608]
```

Somewhere here in this file @ [parseSupabaseCookie](https://github.com/supabase/auth-helpers/blob/db9ce648dd8d160e56bc8ee044359cfeefbdfe95/packages/shared/src/utils/cookies.ts#L57)

Cookies are being set, i've parsed the cookies by hand. Sorry though im unable to debug the nextjs server somehow.

**Comment by silentworks** [comment] 2023-04-17 21:14
> Remember that next 13.3.0 has a problem (fail to parse json) that you can fix by changing the export default function to const and then exporting it below
Any guide on this one or any open issue on the next repo about this that I could have a read about?

**Comment by silentworks** [comment] 2023-04-17 21:17
I'm waiting for some feedback from my previous message above https://github.com/supabase/auth-helpers/issues/497#issuecomment-1510434503 to know if it's fixed in this version before I create a new version of auth-helpers with `jose` as it's dependency. You can see I have an active PR waiting to be merged once I hear from folks in this issue if the above works or not. https://github.com/supabase/auth-helpers/pull/515

**Comment by juanivrs** [comment] 2023-04-18 07:54
> 
vercel/next.js#48447

**Comment by silentworks** [comment] 2023-04-19 18:34
I'm closing this one out as I've published a new version that uses `jose` and it also seems that Vercel has fixed Buffer in NextJS now.

**Closed by silentworks** 2023-04-19 18:34 UTC
Labels: bug

**Comment by mryechkin** [comment] 2023-04-20 03:34
Can confirm the issue is now fixed for me on `next@13.3.0` and `auth-helpers-nextjs@0.6.1` 🎉

**Comment by j1-dev** [comment] 2023-05-08 19:25
I'm having this exact problem with `next@13.4.1` and `auth-helpers-nextjs@0.6.1`

**Comment by aleix10kst** [comment] 2023-05-09 17:09
@j1-dev same here... In my case when I deploy to Vercel I get: 

```
Error: The Edge Function "middleware" is referencing unsupported modules:
- next: stream, fs, url
```

**Comment by Reikon95** [comment] 2023-05-15 12:35
Same issue here, have tried toggling all kinds of versions but no luck at all, was only able to bring my application back online by rolling back to a commit from last week.

I am running:
next v13.1.6
@supabase/auth-helpers-nextjs v.0.5.9 (but have tested on multiple versions)

**Comment by silentworks** [comment] 2023-05-15 12:41
@j1-dev @aleix10kst @Reikon95 If you're having the issue that was fixed it means Vercel/NextJS has changed something again. The issue isn't with the auth-helpers but with NextJS. You should open an issue on their repository.

**Comment by Reikon95** [comment] 2023-05-15 12:45
> @j1-dev @aleix10kst @Reikon95 If you're having the issue that was fixed it means Vercel/NextJS has changed something again. The issue isn't with the auth-helpers but with NextJS. You should open an issue on their repository.

Yeah that adds up, I'll open an issue there. Thanks

**Comment by steeeved** [comment] 2023-08-07 08:54
Worked when I updated next.js and auth-helpers-nextjs

**Comment by twinnytwin22** [comment] 2023-08-25 20:12
> 

Same at the moment. I have 1 app that just didn't auth anymore. No changes, no updates. Weird. Client auth seems to be the issue you tho, if you move your auth to the server via server action or api route I seems to work.

**Comment by arshtec** [comment] 2023-09-16 20:47
> I also have this issue when the cookie token is malformed/invalid format.
> 
> ```
> @supabase/auth-helpers-nextjs: 0.7.4
> @supabase/supabase-js: 2.32.0
> next: 13.4.17
> ```

I have the same issue as well, any possible fixes from the NextJS team?

**Comment by silentworks** [comment] 2023-09-17 10:00
@arshtec this isn't the correct place to ask the NextJS team questions, that would be on their own GitHub repository.
