### ISSUE TITLE
@supabase/auth-helpers-nextjs: `createBrowserSupabaseClient` doesn't work in `next@13.3.0` - `Module not found: Can't resolve 'fs'`

### ISSUE THREAD

**Issue by jankaifer** [supabase/auth-helpers#493] opened 2023-04-06 21:54 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

This package internally imports `next/server` even in browser bundles.
That was not problematic in earlier versions of `next`, but this is an issue in the latest `next@13.3.0`.

This code can't be bundled to a client:
https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/middleware/withMiddlewareAuth.ts#L1-L2

I recommend fixing this using different bundles for each environment with `exports` field in `package.json`, we use that in packages like https://github.com/vercel/otel

## To Reproduce
Try building this:
https://github.com/jankaifer/next-repro-supabase

## Expected behavior

It builds without error.

## Screenshots

```
> @ build /home/pearman/dev/playground/supabase
> next build

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

Failed to compile.

./node_modules/.pnpm/next@13.2.5-canary.34_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@vercel/og/index.node.js
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.2.5-canary.34_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/.pnpm/next@13.2.5-canary.34_biqbaboplfbrettd7655fr4n2y/node_modules/next/server.js
./node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.5.9_7jdpwtii2ojrsp4bzhat4kanty/node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./app/page.tsx


> Build failed because of webpack errors
info  - Creating an optimized production build . ELIFECYCLE  Command failed with exit code 1.
```

## System information

- OS: Linux (NixOS)
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: `2.14.0`
- Version of Node.js: `v18.12.1`

## Additional context

We added `@vercel/og` import in `next/server`. This package doesn't work in the browser and that causes this issue.

`next/server` was never intended to be imported on the client `next` just didn't enforce this.

**Comment by jankaifer** [comment] 2023-04-06 22:14
importing `next/server` doesn't throw on `next@13.2.4` (the last working version) so the workaround is to just stay there before this is fixed.

**Comment by imownbey** [comment] 2023-04-06 22:37
We are seeing this also, FWIW you can safely upgrade to `13.2.5-canary.22` if you are interested. After that it seems to start throwing this error.

**Comment by johnmanjiro11** [comment] 2023-04-07 00:28
I tried next@13.2.4 to latest after I have the same issue.😢
In my case, an error File not found 'tsconfig/base.json" at auth-helpres-nextjs/tsconfig.json > extends, occurred.

**Comment by Aldo111** [comment] 2023-04-07 03:42
Having the same issue as well after migrating from 13.2.4 to 13.3.0 of nextjs.

**Comment by litewarp** [comment] 2023-04-07 07:27
From a quick search, it looks like the current issue is related to [this previous bug](https://github.com/supabase/supabase-js/issues/461).

**Comment by Alexandredc** [comment] 2023-04-07 07:39
Same problem here !

**Comment by wiesson** [comment] 2023-04-07 08:25
Does anyone has an idea how to solve this issue in the meantime?

**Comment by vladutilie** [comment] 2023-04-07 09:23
Hi! Same here.
For me, a downgrade to the 0.5.7 version worked.

**Comment by silentworks** [comment] 2023-04-07 10:51
We are working on resolving this issue and will try and get a fix out today.

**Comment by silentworks** [comment] 2023-04-07 14:14
I just released version **0.6.0** of the `@supabase/auth-helpers-nextjs` which should fix this issue. Please report back here if there are any issues.

**Comment by xinha-sh** [comment] 2023-04-07 14:25
> I just released version **0.6.0** of the `@supabase/auth-helpers-nextjs` which should fix this issue. Please report back here if there are any issues.

This fixes the earlier issue. But now I'm getting bunch of other errors related to Can't resolve 'encoding' in node-fetch package.
![Screenshot 2023-04-07 at 7 50 42 PM](https://user-images.githubusercontent.com/107257599/230624796-2b565b6d-0aa6-4e0d-ae15-ca09db6c7be0.png)

**Comment by silentworks** [comment] 2023-04-07 14:30
@xinha-sh Likely you having a version mismatch, you need to upgrade to the latest `@supabase/supabase-js`. Also worth clearing out your `node_modules` and `package-lock.json` before trying the new version.

**Comment by KajSzy** [comment] 2023-04-07 15:03
Missing module seems to be resolved but getting 
There seems to be an issue with `createMiddlewareSupabaseClient` being used in middleware which uses `Edge Runtime`
![Zrzut ekranu 2023-04-7 o 17 00 43](https://user-images.githubusercontent.com/22811572/230631031-1f02eafc-5828-4974-9534-855379394b56.jpg)

**Comment by riccardolardi** [comment] 2023-04-07 15:05
@KajSzy am seeing the same

**Comment by silentworks** [comment] 2023-04-07 15:49
@KajSzy @riccardolardi that's a warning and not an issue since Buffer isn't used in the case of Edge Runtime and it will fallback to the polyfill implementation of the library. I'm not sure why Next build keeps on showing the warning since it doesn't get used at runtime.

**Comment by silentworks** [comment] 2023-04-07 15:50
I'm closing this one out as the issue from the OP has been resolved.

**Closed by silentworks** 2023-04-07 15:50 UTC
Labels: bug

**Comment by mryechkin** [comment] 2023-04-08 00:22
> @KajSzy @riccardolardi that's a warning and not an issue since Buffer isn't used in the case of Edge Runtime and it will fallback to the polyfill implementation of the library. I'm not sure why Next build keeps on showing the warning since it doesn't get used at runtime.

Hi @silentworks - in my case this looks to be causing the `session` to not be able to be read inside `middleware.js`:

<img width="994" alt="Screenshot 2023-04-07 at 8 05 17 PM" src="https://user-images.githubusercontent.com/5657181/230694341-6b775595-dd2e-4e1b-91a3-e630525f4bd5.png">

```js
const supabase = createMiddlewareSupabaseClient({ req, res });

const {
  data: { session },
} = await supabase.auth.getSession();

console.log({ session });

if (!session) {
  console.log('No session found. Please sign in...');
  return NextResponse.redirect(new URL('/sign-in', req.url));
}
```

This looks to have broke in `0.5.9`, as `0.5.8` and below I don't get this error and the `session` reads fine.

**Comment by stern-shawn** [comment] 2023-04-08 03:06
> Hi @silentworks - in my case this looks to be causing the `session` to not be able to be read inside `middleware.js`:

I'm experiencing this as well with identical code, next `13.2.4` + auth-helpers-nextjs `0.6.0`, and `0.5.9` which had previously worked earlier this week...

Pinning to `0.5.8` also resolves the issue.

```
Failed to parse cookie string: [Error: The edge runtime does not support Node.js 'buffer' module.
Learn More: https://nextjs.org/docs/messages/node-module-in-edge-runtime]
{ session: null }
```

**Comment by batuhanbilginn** [comment] 2023-04-08 14:12
It's weird but on my case, middleware can't reach session on mobile devices. It works on desktop-production but now on mobile.

**Comment by jmcannon** [comment] 2023-04-09 10:23
Started playing with Supabase yesterday with a fresh Next.js install, all boilerplate code from the docs. I'm also facing the middleware issue -  seeing the `Failed to parse cookie string` error and can't get a session in middle.js.

**Comment by silentworks** [comment] 2023-04-09 11:33
@mryechkin @stern-shawn @batuhanbilginn @jmcannon one of you need to provide a minimal reproducible example of this issue also this should be created as a new issue and not tag on to this existing one as the issue the OP posted here was fixed and these aren't the same things.

**Comment by Aldo111** [comment] 2023-04-23 10:32
Hi not sure if still relevant but I still get this error on nextjs 13.3.1


```
error - ./node_modules/next/dist/compiled/@vercel/og/index.node.js:17950:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/next/server.js
./node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./src/app/SupabaseProvider.tsx
```
