### ISSUE TITLE
Reduce size

### ISSUE THREAD

**Issue by enyo** [supabase/auth-helpers#423] opened 2023-01-13 14:33 UTC
# Feature request

I added supabase to my sveltekit app, and my lighthouse score dropped drastically. All I import is `import { createClient } from '@supabase/auth-helpers-sveltekit’` and this is what is imported:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/133277/212344666-520fed88-a188-4b96-8e5c-ebc0e85668bd.png">

Over 80KiB of JS.

Is there a way to reduce this size somehow? For example: is realtime really necessary just for the client?

It’s nearly impossible for me to get a performance score above 90 with supabase.

**Comment by david-plugge** [comment] 2023-01-17 21:21
Is this also an issue without the helpers installed, just plain supabase-js?

**Comment by thorwebdev** [comment] 2023-01-18 05:01
Yah, this is supabase-js feedback really. Closing out as duplicate of https://github.com/supabase/supabase-js/issues/151

**Closed by thorwebdev** 2023-01-18 05:01 UTC
Labels: enhancement
