### ISSUE TITLE
[SvelteKit] AuthApiError: invalid request: both auth code and code verifier should be non-empty

### ISSUE THREAD

**Issue by lucadalli** [supabase/auth-helpers#587] opened 2023-06-15 18:48 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Facing a `AuthApiError: invalid request: both auth code and code verifier should be non-empty` error when attempting to confirm a signup that was initiated on server-side as per [the docs](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#server-side).
Does not occur when the `signUp` call is made on the client.

## To Reproduce

1. Initiate sign up on server-side as per [the docs](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#server-side)
2. Visit confirmation link received via email

## Expected behavior

Sign up is confirmed

## Screenshots

N/A

## System information

- OS: Windows
- Browser N/A
- Version of supabase-js: 2.24.0
- Version of Node.js: 18.13.0

**Comment by potatowave** [comment] 2023-06-15 23:54
Same issue here following the nextjs instructions

**Comment by tholder** [comment] 2023-06-16 04:22
Same issue. Works fine locally.

**Comment by tholder** [comment] 2023-06-16 04:25
Should point out, it seems to actually confirm the email but throws an error. Vercel kicking out:

```
- error AuthApiError: invalid request: both auth code and code verifier should be non-empty
    at /var/task/.next/server/chunks/928.js:3374:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  __isAuthError: true,
  status: 400
}

**Comment by hamishtaplin** [comment] 2023-06-16 09:38
Are you opening the link in the email in the same browser from which you made the original request? It sets the auth code in a cookie so you need to be in the same browser (not in incognito mode) for it to work. This caught me out and has obvious implications around a common user flow (sending the request on one device, opening the link on another)

**Comment by krsnaa** [comment] 2023-06-16 11:21
I can confirm that this also happens with PKCE OAuth calls.

**Comment by silentworks** [comment] 2023-06-16 12:44
This is how the `pkce` flow works as outlined by @hamishtaplin above. The browser in which the request was made has to be the same browser the link should be opened in. If it is the same browser and you are having this issue please create a minimal reproducible example repo with the issue. I have a few example projects using the `pkce` flow on the server side and don't have this issue with any of them. You can check one out here https://github.com/supabase-community/supabase-by-example/tree/main/reset-flow/sveltekit.

**Comment by silentworks** [comment] 2023-06-16 13:12
Closing this as it's a duplicate of #545

**Closed by silentworks** 2023-06-16 13:12 UTC
Labels: bug

**Comment by lucadalli** [comment] 2023-06-18 15:33
> This is how the `pkce` flow works as outlined by @hamishtaplin above. The browser in which the request was made has to be the same browser the link should be opened in. If it is the same browser and you are having this issue please create a minimal reproducible example repo with the issue. I have a few example projects using the `pkce` flow on the server side and don't have this issue with any of them. You can check one out here https://github.com/supabase-community/supabase-by-example/tree/main/reset-flow/sveltekit.

I am calling `signUp` in a `trpc` procedure. This is likely failing because accessing/setting the cookie is not possible with my current `trpc` configuration.

**Comment by Nicolasvegam** [comment] 2023-07-10 14:41
> Are you opening the link in the email in the same browser from which you made the original request? It sets the auth code in a cookie so you need to be in the same browser (not in incognito mode) for it to work. This caught me out and has obvious implications around a common user flow (sending the request on one device, opening the link on another)

This is the actual problem, same happens ins nextjs!

**Comment by leikoilja** [comment] 2023-12-02 14:39
same issue happens when on my nextjs server when i use google auth from phone

**Comment by wiwa** [comment] 2024-07-29 23:49
I believe the issue (at least with SvelteKit) has to due to with invalid `CookieMethods` config in the documentation: https://github.com/orgs/supabase/discussions/21183#discussioncomment-10184740
