### ISSUE TITLE
npm install fails for @supabase/auth-helpers-sveltekit

### ISSUE THREAD

**Issue by secretgspot** [supabase/auth-helpers#278] opened 2022-10-02 01:03 UTC
# Bug report

## Describe the bug

unable to resolve dependency tree

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. come to any of the official sources such as npmjs.com, see that package was last updated few days ago and is at version 0.7.1 latest
2. run "npm i @supabase/auth-helpers-sveltekit"
3. watch screen fill with red

## Expected behavior

stuff working as it should!

## Screenshots

```txt
└ $ npm i @supabase/auth-helpers-sveltekit
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: muniapp@0.0.1
npm ERR! Found: @supabase/supabase-js@2.0.0-rc.10
npm ERR! node_modules/@supabase/supabase-js
npm ERR!   @supabase/supabase-js@"^2.0.0-rc.10" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @supabase/supabase-js@"^1.35.3" from @supabase/auth-helpers-sveltekit@0.7.1
npm ERR! node_modules/@supabase/auth-helpers-sveltekit
npm ERR!   @supabase/auth-helpers-sveltekit@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\xxx\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Local\npm-cache\_logs\2022-10-02T00_53_00_263Z-debug-0.log
```

## System information

```json
	"devDependencies": {
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"svelte": "^3.46.0",
		"vite": "^3.1.0"
	},
	"type": "module",
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.0",
		"@supabase/supabase-js": "^2.0.0-rc.10"
	}
```

## Additional context

this is so frustrating,  auth-helper not playing nice with older version of supabase-js so need to update supabase-js but then current auth-helper doesn't like latest version of supabase-js, which in turn doesn't like earlier version of auth-helper.  I feel like developers don't even bother testing, checking, updating documentation and just do it for the sake of github heatmap being filled up

**Comment by silentworks** [comment] 2022-10-02 12:48
From the looks of your system information, you are trying to install auth-helpers-sveltekit with the latest version of the supabase-js library. We haven't released a version that works with that version as yet, the version released was to resolve issues with the breaking changes in SvelteKit RC. If you look at the peer dependency of the [package.json](https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/package.json#L68) you will notice its stated to work with `^1.35.3`, so only versions in the `v1` of the supabase-js library.

**Comment by yzn-h** [comment] 2022-10-02 17:58
same here I'm trying to run any of the examples all of them don't work

**Comment by david-plugge** [comment] 2022-10-02 18:06
> same here I'm trying to run any of the examples all of them don't work

A bit more input on what exactly is not working or a reproduction would very handy

**Comment by tomsharratt** [comment] 2022-10-02 18:28
Are there any plans to update this for v2 RC compatibility soon?

**Comment by david-plugge** [comment] 2022-10-03 07:02
@tomsharratt I've been playing around a bit, you can take a look at my [fork](https://github.com/david-plugge/supabase-auth-helpers/blob/next/packages/sveltekit). It will probably change before the release but if you want to use it feel free. Also make sure to check if it's actually working correct, I didn't do a lot of testing.

To be concise the v2 rc update will take a bit more time to solidify the api and avoid breaking changes.

**Comment by yzn-h** [comment] 2022-10-03 12:27
> > same here I'm trying to run any of the examples all of them don't work
> 
> A bit more input on what exactly is not working or a reproduction would very handy

https://user-images.githubusercontent.com/63852512/193576367-64564a67-ed47-427d-a08e-cb6f65eaff54.mp4

**Comment by Nisthar** [comment] 2022-10-10 10:01
> @tomsharratt I've been playing around a bit, you can take a look at my [fork](https://github.com/david-plugge/supabase-auth-helpers/blob/next/packages/sveltekit). It will probably change before the release but if you want to use it feel free. Also make sure to check if it's actually working correct, I didn't do a lot of testing.
> 
> To be concise the v2 rc update will take a bit more time to solidify the api and avoid breaking changes.
> 
> Edit:
> 
> the package is not published, you'd have to build it yourself.

Can you tell me how do you use the build files in a sveltekit project?

**Comment by david-plugge** [comment] 2022-10-10 10:05
@Nisthar copy the contents of [this folder](https://github.com/david-plugge/supabase-auth-helpers/tree/next/packages/sveltekit/src) inside `src/lib/supabase-auth`. Adjust your `src/app.d.ts` and remove the `app.d.ts` file from the copied folder. That should be it. You can now import everything you need from `$lib/supabase-auth`.

**Comment by Nisthar** [comment] 2022-10-10 16:11
> @Nisthar copy the contents of [this folder](https://github.com/david-plugge/supabase-auth-helpers/tree/next/packages/sveltekit/src) inside `src/lib/supabase-auth`. Adjust your `src/app.d.ts` and remove the `app.d.ts` file from the copied folder. That should be it. You can now import everything you need from `$lib/supabase-auth`.

I get this error

![image](https://user-images.githubusercontent.com/11994157/194909838-f9cbfbb6-3508-4919-8864-9023ac600eb2.png)
do i need to copy auth-helpers-shared folder as well?

**Comment by Nisthar** [comment] 2022-10-10 17:21
> @Nisthar copy the contents of [this folder](https://github.com/david-plugge/supabase-auth-helpers/tree/next/packages/sveltekit/src) inside `src/lib/supabase-auth`. Adjust your `src/app.d.ts` and remove the `app.d.ts` file from the copied folder. That should be it. You can now import everything you need from `$lib/supabase-auth`.

I copied the `auth-helpers-shared` as well.
But its not working for me. I get errors like
![image](https://user-images.githubusercontent.com/11994157/194914802-a0994da8-89e7-4f64-b4b9-525aee8e8160.png)
![image](https://user-images.githubusercontent.com/11994157/194914820-f4bb8e7d-f872-48bb-9ced-d2247eb63663.png)

**Comment by Nisthar** [comment] 2022-10-10 17:53
Ok somehow `git clone https://github.com/david-plugge/supabase-auth-helpers.git` is cloning the old version

**Comment by Nisthar** [comment] 2022-10-10 17:59
> @Nisthar copy the contents of [this folder](https://github.com/david-plugge/supabase-auth-helpers/tree/next/packages/sveltekit/src) inside `src/lib/supabase-auth`. Adjust your `src/app.d.ts` and remove the `app.d.ts` file from the copied folder. That should be it. You can now import everything you need from `$lib/supabase-auth`.

I am getting this error:
![image](https://user-images.githubusercontent.com/11994157/194926725-fd72847e-0ff2-42b2-9308-99a1a4c07a55.png)

**Comment by Nisthar** [comment] 2022-10-10 18:22
> @Nisthar copy the contents of [this folder](https://github.com/david-plugge/supabase-auth-helpers/tree/next/packages/sveltekit/src) inside `src/lib/supabase-auth`. Adjust your `src/app.d.ts` and remove the `app.d.ts` file from the copied folder. That should be it. You can now import everything you need from `$lib/supabase-auth`.

![image](https://user-images.githubusercontent.com/11994157/194929900-756f94e8-b9ee-42ef-9bdc-fd1038d0e220.png)

**Comment by enesbala5** [comment] 2022-10-20 22:06
For me what worked was uninstalling the 2.0.3 version of supabase-js and installing 2.0.0

**Comment by david-plugge** [comment] 2022-10-20 23:34
The auth helpers are released for v2 now so there shouldn´t be an issue anymore.
l´ll close this issue now, feel free to open it again if you encounter any issues (or create a new issue)

**Closed by david-plugge** 2022-10-20 23:34 UTC

**Comment by samhsabin** [comment] 2023-12-29 04:47
Having this same issue in 2023(bout to be 2024 in a few days). Just following the "Build a User Management App with SvelteKit" tutorial and getting a similar issue:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: supabase-sveltekit@0.0.1
npm ERR! Found: @sveltejs/kit@2.0.6
npm ERR! node_modules/@sveltejs/kit
npm ERR!   dev @sveltejs/kit@"^2.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @sveltejs/kit@"^1.15.4" from @supabase/auth-helpers-sveltekit@0.10.7
npm ERR! node_modules/@supabase/auth-helpers-sveltekit
npm ERR!   @supabase/auth-helpers-sveltekit@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
I came to Supabase from Appwrite because I was having similar problems with Appwrite documentation producing code that was unusable. Just a bit frustrated. Would love any help to resolve this.
