### ISSUE TITLE
Frequent User Logouts / Invalidated Sessions - SvelteKit

### ISSUE THREAD

**Issue by wattsjs** [supabase/auth-helpers#443] opened 2023-02-09 01:06 UTC
I am opening this as a bug report to see if any other users of this library are experiencing frequent user logouts?

I have not yet been able to pinpoint exactly why this happens but my users report that they are logged out of their sessions around 3-4 times per day at random times.

I'm not sure where to begin with troubleshooting this as I have not been able to replicate the issue on my local machine.

My understanding was that every machine will have a unique cookie and session and therefore a unique `refreshToken`, so their session should not be invalidated that frequently.

I noticed that if I attempt to re-use an authentication magic link that is expired/used, my session will be cleared. Is this defined behaviour? I can't seem to find where this happens in the source. Is it possible to hit this same behaviour when there is a race condition of token refreshes across tabs?

- Assuming a user does not clear their cookies - what would cause a user's session to be invalidated and cleared? Or would the session theoretically last forever? 
- Are there any reports of the token refresh issue between multiple tabs still being present?
- Would increasing the refresh token reuse interval help?
- How best can I begin to troubleshoot this and possibly work out what is happening?

Apologies for the vague report - it *appears* something odd is happening here however I'm not sure what.

**Comment by wattsjs** [comment] 2023-02-09 01:40
Thinking this could be related to [refreshSession](https://github.com/supabase/auth-helpers/issues/414) 

What is the behaviour in the following scenario:

- User has multiple tabs open on the same browser (=same session)
- User refreshes one tab that causes a SSR to happen with a call to `getServerSession`, and the `expires_at` is within 60 seconds to it forces a refresh. (seems like the default for `goTrue` is 30s)
- Supabase clients in other tabs are not aware of this change and therefore attempt to refresh the token, which falls outside of the 10s reuse interval. This causes an invalid response which then invalidates the whole session and logs the user out?

I'm not sure if this is correct - I will attempt to raise the reuse interval to 30s and see if it solves the issue

**Comment by j4w8n** [comment] 2023-02-09 08:21
If this only happens when multiple tabs are involved, gotrue-js 2.11.0 addresses this. supabase-js has not been updated to strictly require this version yet, but I'm sure there is a way to update to it.

https://github.com/supabase/gotrue-js/pull/566

**Comment by wattsjs** [comment] 2023-02-09 21:42
Thanks @j4w8n , not sure if this is in fact related as it seems to be happening after an explicit error.

Left a few session open overnight and woke up to cleared cookies and the following in the console, not entirely sure if this is related to `auth-helpers` but I don't now why it would be clearing cookies if it is not.

```js
Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

setInterval (async) |   |  
-- | -- | --
  | (anonymous) | @ | _layout.svelte-4e3e6d27.js:1
  | nt | @ | index-b4d01b3a.js:1
  | (anonymous) | @ | index-b4d01b3a.js:4
  | X | @ | index-b4d01b3a.js:4
  | tn | @ | index-b4d01b3a.js:4
  | Wt | @ | start-0d13c73b.js:1
  | je | @ | start-0d13c73b.js:1
  | _hydrate | @ | start-0d13c73b.js:1
  | await in _hydrate (async) |   |  
  | ln | @ | start-0d13c73b.js:1
  | (anonymous) | @ | VM245:4


```

**Comment by andperks6** [comment] 2023-03-01 04:37
I haven't noticed logouts but I have noticed frequent onAuthStateChange events (in examples this is where invalidation`invalidate('supabase:auth');` is called), not with multiple tabs. 

I narrowed it down to switching to any other (unrelated) tab and switching back in the same window. The event is always the same - `SIGNED_IN` - so I'm not sure why this is picked up as a change event.  This is still an issue on the `sveltekit-overhaul` branch

More of a workaround than a fix but If I store the given state in a svelte store I no longer have an invalidation.

**Comment by j4w8n** [comment] 2023-03-01 11:45
@andperks6 I suspect you're seeing the effects of go-true code for a private function called _handleVisibiltyChange.

It sets up some listeners for window and tab focus - or something like that. During the process, the code fires _recoverAndRefresh. If there is a session in storage, the SIGNED_IN event is fired. I don't know why they chose to fire the event.  

If the event is causing an issue for you, you may want to create an issue in the go-true repo.

**Comment by j4w8n** [comment] 2023-03-01 11:49
@wattsjs are you still having issues with the 2.8.0 version of supabase-js?

**Comment by wattsjs** [comment] 2023-03-01 11:55
@j4w8n yes I believe I was still having issues, although they may have been reduced. At the moment I have resorted to using a JWT expiry of 1 week and it seems to have solved the issue - I saw some discussion around there being a bug that would clear the cookie serverside if there were some conditions met inside of the refresh window. So the idea was that if the user gets 'randomly' logged out once a week - that is okay 🙂 At the moment I don't have many security concerns to worry about the long expiry.

When the new auth-helpers are released I'll give them a crack - as I've seen the amazing work of @david-plugge that looks to improve upon the way cookies are handled!

**Comment by david-plugge** [comment] 2023-03-01 14:03
@wattsjs thanks for your kind words!

@andperks6 as @j4w8n already mentioned this is caused by the way gotrue works internally.
Instead of calling `invalidate('supabase:auth')` every time you can check for the event type.
```ts
onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    invalidate('supabase:auth');
  }
})
```
But then you have to manually call `invalidate('supabase:auth')` whenever you signin or signout. Probably a good addition to the docs!

**Comment by wattsjs** [comment] 2023-03-01 14:10
Thanks @david-plugge ! I actually don't think this is the issue for me though - I do in fact already filter out SIGNED_IN (I check if the auth token has changed, so that I can still catch a SIGNED_IN event from another tab if there are two tabs sitting on the login page)

I think this may be some issue with the auth-helpers sveltekit internal at the moment with the way they handle cookies. I believe you may have been involved in the discussion I saw around this issue? Would that make any sense to you that there may be some edge cases with the current implementation that may be addressed with your new approach?

**Comment by david-plugge** [comment] 2023-03-01 14:25
> What is the behaviour in the following scenario:
> 
> * User has multiple tabs open on the same browser (=same session)
> * User refreshes one tab that causes a SSR to happen with a call to `getServerSession`, and the `expires_at` is within 60 seconds to it forces a refresh. (seems like the default for `goTrue` is 30s)
> * Supabase clients in other tabs are not aware of this change and therefore attempt to refresh the token, which falls outside of the 10s reuse interval. This causes an invalid response which then invalidates the whole session and logs the user out?

The other tabs clients should just pick up the updated session whenever `supabase.auth.getSession()` is called so this should not be the problem (it´s called internally for every request).

I can´t really think of any reason other than syncing issues but this surely needs some more testing. Have you tried the latest version and still ran into these issues?

**Comment by silentworks** [comment] 2023-04-07 16:23
Closing this one out as we can't reproduce it.  If this is still happening provide a reproducible example showing this behavior and then we can investigate more.

**Closed by silentworks** 2023-04-07 16:23 UTC
Labels: bug
