### ISSUE TITLE
[BUG][Next 13][API Route][createRouteHandlerClient] Unable to obtain a session

### ISSUE THREAD

**Issue by atanaskanchev** [supabase/auth-helpers#585] opened 2023-06-13 07:37 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unable to obtain the session in Next 13 api route handler

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

### api route handler `apps/web/src/app/api/contact/route.ts`
```ts
import { createRouteHandlerClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'

export async function GET() {
  const supabase = createRouteHandlerClient({ cookies })

  const { data, error } = await supabase.auth.getSession()

  return NextResponse.json({ data, error })
}
```

### response
```json
{
  "data": {
    "session": null
  },
  "error": null
}
```

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: `"@supabase/auth-helpers-nextjs": "0.7.2"`
- Version of Node.js: 18

**Comment by grahamorrell** [comment] 2023-06-13 12:14
How did you invoke the Route Handler?  Was it, by any chance, using a fetch from a React Server Component?

**Comment by atanaskanchev** [comment] 2023-06-13 12:18
Hi, yes actually, it’s a fetch call from a rsc. I’ve added the session token as a cookie to the fetch header, but the session was still null.

**Comment by grahamorrell** [comment] 2023-06-13 12:41
We just hit the same issue - I've outlined how we resolved in #566

**Comment by silentworks** [comment] 2023-06-16 13:15
Please share your exact setup as the description you gave above doesn't include the fetch call you mentioned. When giving bug report please provide all details to replicate the issue, it's also better to create a minimal reproducible repository.

**Comment by silentworks** [comment] 2023-06-16 19:35
This is not a bug its just how fetch requests work. You need to pass the cookies along (as @grahamorrell stated) if you want to access them in the request.

```ts
import { headers } from "next/headers";

const res = await fetch("http://localhost:3000/api/contact", {
  headers: {
    cookie: headers().get("cookie") as string,
  },
});
```

**Closed by silentworks** 2023-06-16 19:35 UTC
Labels: bug
