### ISSUE TITLE
NextJS 13: supabase-auth-token Cookie being deleted soon after Sign In when using OAuth

### ISSUE THREAD

**Issue by patrickbindelli** [supabase/auth-helpers#437] opened 2023-01-28 03:50 UTC
# Bug report

## Describe the bug

The supabase-auth-token gets created but soon after gets deleted when using NextJS 13 with regular pages directory and trying to sign in using OAuth provider

## To Reproduce

1. Create basic auth system following the [Supabase Auth with Next.js](https://supabase.com/docs/guides/auth/auth-helpers/nextjs) guide and create some page like: 

``` 
export default function Home() {
  const router = useRouter();
  const supabase = useSupabaseClient();

  const signOut = async () => {
    await supabase.auth.signOut();
    router.push('/auth');
  };

  return (
    <>
      <Head>
        <title>Example</title>
        <meta
          name="description"
          content="Example."
        />
      </Head>

      <main>
        <button onClick={signOut}>Signout</button>
        <p>Testing</p>
      </main>
    </>
  );
}
```
2. Try signing in using OAuth provider (e.g using Auth UI to sign in via GitHub)
3. Try getting session using `getServerSideProps`:

```
export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const supabase = createServerSupabaseClient(ctx);
  const {
    data: { session },
  } = await supabase.auth.getSession();


  // returns the session when i log-in using a provider
  // but then returns null if i reload the page
  console.log(session);

  if (!session)
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      },
    };

  return {
    props: {
      initialSession: session,
    },
  };
}
```

4. See that it does not keep the session cookie upon refreshing the page

## Expected behavior

Expected cookie being kept for retrieving while signed in, like when using NextJS 12

## Screenshots

Using fast3G network throttling:
![image](https://user-images.githubusercontent.com/68287231/215240621-7fd081d5-355c-486f-95a4-5a0e0f7abf12.png)

Using no network throttling, after signing in:
![image](https://user-images.githubusercontent.com/68287231/215240669-b1f3f7ed-b97b-47b3-a6af-a323e7768cf8.png)

## System information

- OS: Windows
- Browser: chrome
- Version of supabase-js: v2.5.0
- Version of Node.js: v18.12.1
- Version of Next: v13.1.2

## Additional context

If i use network throttling i can get the cookie to be kept sometimes. Maybe some unexpected async behaviour?

**Comment by willisplummer** [comment] 2023-01-28 14:40
I'm running into this as well

**Comment by 4ortytwo** [comment] 2023-01-30 20:29
I had a similar problem and solved it by changing the `storage` in `auth` when creating the client.

```ts
import { Database } from '@src/@types/database.types';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { deleteCookie, getCookie, setCookie } from 'cookies-next';

export const supabase: SupabaseClient<Database> = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL as string,
  process.env.NEXT_PUBLIC_SUPABASE_API_KEY as string,
  {
    auth: {
      storageKey: 'supabase-auth-token',
      storage: {
        getItem(key) {
          return getCookie(key);
        },
        setItem(key, value) {
          return setCookie(key, value, {
            httpOnly: false,
            sameSite: 'lax',
            maxAge: Date.now() + 1000 * 60 * 60 * 24 * 365,
            expires: new Date(Date.now() + 1000 * 60 * 60 * 24 * 365),
            secure: typeof document !== 'undefined' && document.location?.protocol === 'https',
          });
        },
        removeItem(key) {
          return deleteCookie(key);
        },
      },
    },
  },
);
```

**Comment by willisplummer** [comment] 2023-01-30 22:44
[4ortytwo](https://github.com/4ortytwo) do you think it's a problem with the next helper then and using `@supabase/supabase-js` for `createClient` is the trick

**Comment by willisplummer** [comment] 2023-01-31 01:43
switching from `import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs'` to  `import { createClient } from '@supabase/supabase-js'` fixed my issue

**Comment by claudiuandrei** [comment] 2023-01-31 04:46
The same problem is happening in Remix

**Comment by chenb67** [comment] 2023-02-02 08:12
I stopped passing initialSession from the server props and it seems to help, not totally sure yet though.

**Comment by chenb67** [comment] 2023-02-08 19:50
@patrickbindelli another thing we found - supabase passes the access token using # parameters to overcome the url length restriction, so your server side client doesn't get the redirected access_token and then redirects elsewhere and loses it. to fix it don't redirect inside getServerSideProps

**Comment by silentworks** [comment] 2023-04-07 16:07
Can't reproduce and closing this one out. If this is still an issue please provide a reproducible example repo with the issue.

**Closed by silentworks** 2023-04-07 16:07 UTC
Labels: bug

**Comment by whollacsek** [comment] 2023-04-07 16:17
This problem exists please don't close it. Can you guys dogfood this
internally? It happens randomly so it's going to be difficult to reproduce
unfortunately

**Comment by silentworks** [comment] 2023-04-07 22:55
This will stay closed unless someone can provide a reproducible example. We use NextJS and haven't hit this issue, so someone will need to provide a reproduction of this in order for us to be able to see the issue.

**Comment by gatchan0807** [comment] 2023-05-04 11:17
Same bug(maybe) occurred on my application. so, I report to this issue.

### Referenced
https://supabase.com/docs/guides/auth/auth-helpers/nextjs#server-side-rendering-ssr

```
import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs'

export default function Profile({ user }) {
  return <div>Hello {user.name}</div>
}

export const getServerSideProps = async (ctx) => {
  // Create authenticated Supabase Client
  const supabase = createServerSupabaseClient(ctx)
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession()

  if (!session)
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }

  return {
    props: {
      initialSession: session,
      user: session.user,
    },
  }
}
```

### System information
- OS: Mac
- Browser: Chrome
- Version of supabase-js: `v2.21.0`
- Version of @supabase/auth-helpers-nextjs: `v0.6.1`
- Version of Node.js: `v16.20.0`
- Version of Next: `v13.3.4`

### Error message

```
error - [rendering] [root of the server]/profile  Error during SSR Rendering
  TypeError: Cannot read properties of undefined (reading 'supabase-auth-token')
  
Debug info:
- TypeError: Cannot read properties of undefined (reading 'supabase-auth-token')
      [at getCookie (/path/to/application/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:76:33)]
      [at createServerSupabaseClient (/path/to/application/node_modules/@supabase/auth-helpers-shared/dist/index.js:360:44)]
      [at Object.createServerSupabaseClient (/path/to/application/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:71:68)]
      at getServerSideProps (src/pages/profile.tsx:10:20) [/path/to/application/.next/server/pages/chunks/src_pages_profile.tsx_9d1d4e._.js:27:118]
      6 | }
      7 | 
      8 | export const getServerSideProps: GetServerSideProps = async (ctx) => {
      9 |   // Create authenticated Supabase Client
         |                    v
      10 +   const supabase = createServerSupabaseClient(ctx);
         |                    ^
      11 |   // Check if we have a session
      12 |   const {
      13 |     data: { session },
      14 |   } = await supabase.auth.getSession();
   
      [at /path/to/application/node_modules/next/dist/server/render.js:565:26]
      [at /path/to/application/node_modules/next/dist/server/lib/trace/tracer.js:113:36]
      [at NoopContextManager.with (/path/to/application/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)]
      [at ContextAPI.with (/path/to/application/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)]
      [at NoopTracer.startActiveSpan (/path/to/application/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18086)]
      [at ProxyTracer.startActiveSpan (/path/to/application/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18847)]
      [at /path/to/application/node_modules/next/dist/server/lib/trace/tracer.js:102:107]
      [at NoopContextManager.with (/path/to/application/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)]
      [at ContextAPI.with (/path/to/application/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)]
      [at NextTracerImpl.trace (/path/to/application/node_modules/next/dist/server/lib/trace/tracer.js:102:32)]
      [at Object.renderToHTML (/path/to/application/node_modules/next/dist/server/render.js:560:51)]
      [at processTicksAndRejections (node:internal/process/task_queues:96:5)]
      at async runOperation (/turbopack/[next]/internal/page-server-handler.tsx:240:26) [/path/to/application/.next/server/pages/chunks/[next]_internal_page-server-handler.tsx_6b6c06._.js:291:30]
      at async (/turbopack/[next]/internal/page-server-handler.tsx:80:19) [/path/to/application/.next/server/pages/chunks/[next]_internal_page-server-handler.tsx_6b6c06._.js:184:25]
```
note: a little process the messages and referenced code. 

1. Mask file path on error messages
2. Add type specification on referenced code (use `GetServerSideProps` type.)

### Remarks

- No occurred that on API Routes. 
  - ref: https://supabase.com/docs/guides/auth/auth-helpers/nextjs#server-side-rendering-ssr 
- Not have `req.cookies['supabase-auth-token']` properties and `req.cookies` in `ctx.req` when `getServerSideProps` 
  - https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/index.ts#L94
