### ISSUE TITLE
`createClientComponentClient` automatically handles `/callback?code=`

### ISSUE THREAD

**Issue by arobert93** [supabase/auth-helpers#626] opened 2023-08-09 12:57 UTC
While trying to fix this [issue](https://github.com/supabase/auth-helpers/issues/619) by moving the `/callback` `GET` route to a `Page` I noticed that when I'm creating the Supabase client using `createClientComponentClient` it automatically handles the route params and redirects. From my own perspective, we lose the control over the navigation, params check, etc. and I don't think that the client creating should automatically handle the page state.

**Comment by silentworks** [comment] 2023-09-04 14:30
Closing this one out as I'm not able to reproduce this issue. Please do re-open if you have a reproducible example repo showing this behaviour.

**Closed by silentworks** 2023-09-04 14:30 UTC
Labels: bug
