### ISSUE TITLE
nextjs 13 / PKCE flow is not supported on signups with autoconfirm enabled

### ISSUE THREAD

**Issue by bmichotte** [supabase/auth-helpers#569] opened 2023-05-30 08:57 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Following the [documentation](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#migration-guide) for auth with nextjs13, 
I receive an error _AuthApiError: PKCE flow is not supported on signups with autoconfirm enabled_ when I try to signup a user.

I tried both client and server action versions without success. 

## System information

- OS: macOS
- Version of supabase-js: 1.64.8
- Version of supabase/auth-helpers-nextjs: 0.7.0
- Version of Next.js: 13.4.4

## Additional context

I'm currently working on a self-hosted version of supabase for the development.

**Comment by regalstreak** [comment] 2023-05-30 22:24
Locally, I just had to set `email_confirmations` as `true` to get rid of this

Looks like PKCE is going to be the only flow they'll be [supporting](https://github.com/supabase/auth-helpers/issues/562#issuecomment-1564158745) 
![image](https://github.com/supabase/auth-helpers/assets/7759208/0c81f25f-dcb6-4b5b-a775-2766a6944efa)

**Comment by xvvvyz** [comment] 2023-06-01 20:44
> Locally, I just had to set email_confirmations as true to get rid of this

I get an internal server error on sign up when I try this locally.

```
{"auth_event":{"action":"user_confirmation_requested","actor_id":"454c6bc6-94f5-4869-a208-5543c4a67173","actor_username":"email@example.com","actor_via_sso":false,"log_type":"user","traits":{"provider":"email"}},"component":"api","error":"failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: permission denied for table flow_state (SQLSTATE 42501)","level":"error","method":"POST","msg":"Unhandled server error: failed to close prepared statement: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02): ERROR: permission denied for table flow_state (SQLSTATE 42501)","path":"/signup","referer":"","remote_addr":"172.20.0.1","time":"2023-06-01T20:42:39Z","timestamp":"2023-06-01T20:42:39Z"}
```

**Comment by liawifelix** [comment] 2023-06-04 12:09
> Locally, I just had to set `email_confirmations` as `true` to get rid of this
> 
> Looks like PKCE is going to be the only flow they'll be [supporting](https://github.com/supabase/auth-helpers/issues/562#issuecomment-1564158745) ![image](https://user-images.githubusercontent.com/7759208/242110968-0c81f25f-dcb6-4b5b-a775-2766a6944efa.png)

It works, thanks a lot

**Comment by estebangarcia21** [comment] 2023-06-05 15:23
For those who still want to disable email confirmations locally, my workaround was to manually set the verification time to the current date in the database and sign the user in with `prisma.supabase_auth_user.update`

```js
const { data } = await supabase.auth.signUp({ email, password });

const verificationTime = new Date().toISOString();

// Update the email_confirmed_at and confirmation_sent_at columns from the auth.users table.
await prisma.users.update({
  data: {
    email_confirmed_at: verificationTime,
    confirmation_sent_at: verificationTime
  },
  where: { id: data.user.id }
});

const { data: _data } = await supabase.auth.signInWithPassword({ email, password });

const session = _data.session;
```

**Comment by byamasu-patrick** [comment] 2023-06-13 10:07
@bmichotte has this already been fixed?
I can also confirm that my code is working perfectly fine but when I try to signup with email I am getting this error.

**PKCE flow is not supported on signups with autoconfirm enabled**

I disabled **Confirm email** inside Auth Providers in supbase I don't want to see an email being sent when the user create an account. Just after disablingi am getting that error message from supabase. Is there any solution for this issue from the supabase team?

**Comment by silentworks** [comment] 2023-06-15 17:39
@byamasu-patrick As the error stated you can't use the `pkce` flow with confirm email turned off. The latest versions of auth-helpers which support the app router (which now mean everything can be done server side) requires `pkce` for this to work.

**Comment by tholder** [comment] 2023-06-16 04:38
PKCE flow with email confirmation though seems to be suffering another bug https://github.com/supabase/auth-helpers/issues/587

**Comment by jramiroz98** [comment] 2023-06-16 19:35
You have to roll back to version 0.9.4
At least that's how it worked for me using SvelteKit

**Comment by byamasu-patrick** [comment] 2023-06-19 16:29
@jramiroz98 I will try your approach and see if it is going to work with. Because my goal is to totally disable the default behavior when someone create an account the deafault confirmation email should not be sent to the user.

**Comment by eialanjones** [comment] 2023-07-01 22:19
Another workaround:

// Create a "admin client"
import { createClient } from '@supabase/supabase-js';

export const SupabaseAdmin = (req?) => {
  return createClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE,
  );
};

// then use it to create the new user
const {
      data: { user },
    } = await SupabaseAdmin().auth.signUp({
      email: email,
      password,
    });

// then log in using the serverside supabase normally 
await supabase.auth.signInWithPassword({ email, password });

**Comment by i-bsd** [comment] 2023-07-02 02:02
> Locally, I just had to set `email_confirmations` as `true` to get rid of this
> 
> Looks like PKCE is going to be the only flow they'll be [supporting](https://github.com/supabase/auth-helpers/issues/562#issuecomment-1564158745) ![image](https://user-images.githubusercontent.com/7759208/242110968-0c81f25f-dcb6-4b5b-a775-2766a6944efa.png)

This is not a fix. Nor is using supabase admin client-side.

This is a really frustrating update as it adds a lot of friction to new customer signups making them check their email.

**Comment by StockBet** [comment] 2023-07-02 15:33
yes exactly. why is the default method the one with highest friction?? smh bruh

**Comment by piccinnigius** [comment] 2023-07-03 18:20
for me doesn't work, in local environment created user by hand for now :/

**Comment by skoshx** [comment] 2023-07-03 23:34
I hope someone from the Supabase teams notices this, it is totally unacceptable, that in this day and age we should start requiring our users to confirm their emails like this was back in 2015. 

Customers want to log in with no friction, that's why there is magic link log in.

I just upgraded to the PKCE flow, and now I realize that I will need to go back to using the old flow, because PKCE doesn't work if you want to manually send the login link email (because you want it to be branded)...

**Comment by i-bsd** [comment] 2023-07-03 23:38
> I hope someone from the Supabase teams notices this, it is totally unacceptable, that in this day and age we should start requiring our users to confirm their emails like this was back in 2015.
> 
> Customers want to log in with no friction, that's why there is magic link log in.
> 
> I just upgraded to the PKCE flow, and now I realize that I will need to go back to using the old flow, because PKCE doesn't work if you want to manually send the login link email (because you want it to be branded)...

Exactly. I'm sure we're going to lose sales forcing new customers to jump through hoops to create an account.

One though I had (haven't tried it yet) is to use NextJS server actions to use supabase admin to add the customer, but I don't know if this feasible or secure, plus it's still an alpha feature. Might be the only way to do this if supabase don't correct the changes they've made.

**Comment by skoshx** [comment] 2023-07-04 00:06
@thorwebdev @silentworks Sorry for the mention, but in this case it seems warranted, as the implications of this has a massive impact on Developer Experience.

Following discussions in #562 it became apparent that `pkce` flow is the only one supported going forward. Also it became apparent that with the `pkce` flow the Developers using Supabase are now forced to have their customers confirm emails upon signup, adding friction to both the Developer Experience as well as the customer experience. (Also as an aside, I'm sending magic links manually using `.generateLink`, which also breaks the whole login, because it doesn't send the confirmation email)

Following discussions in #567 it becomes apparent that the migration to the `pkce` flow complicates other types of flows, such as the one in this issue. There doesn't seem to be clear answers to many of the problems us Developers are facing with this new flow. Also, the conclusion seems to be that "In a nutshell, magic links no longer work with `pkce`, use the login code instead" (which once again adds friction especially to users not too familiar with login codes)...

I would like to hear a bit more about the future of Supabase as an auth provider... Is Supabase completely going to throw away magic links, and force users of their auth systems to have to confirm their emails going forward?

I guess what I'm curious to understand is, why make all these changes that seem to have been released and pushed towards so hastily, without exploring the many repercussions of them, and with seemingly little care for the decrease in Developer Experience?

Ps. I hope the answer isn't gonna be to "just use `0.9.x`", because in that case we would be stuck on that version forever😂

**Comment by silentworks** [comment] 2023-07-04 13:10
Hey @skoshx thanks for your detailed points here I will try and explain what happened and what we are doing to rectify this.

Firstly this isn't a marketing gimmick (i.e your statement in a previous post `(because you want it to be branded)`) this was purely an engineering oversight mainly on my part, we had this feature in pre-release for months before we decided to release it as a full release, at that point we didn't get any feedback about any of the flows not working or not being ideal, I tested out a most of these flows but only on one device/browser and also I always had email confirmation on as this is how most services I've interacted with has it setup. One of the main push for having `pkce` in all the flows was to fix our server-side story, before there was an hard requirement on the client-side in order to do signUp's and signIn's with Supabase auth, the `pkce` flow meant there was now a way to do this via the server-side only without the client being involved at all.

Rectifying this isn't as straight forward as one might think it is as we have to make some changes internally to our systems hence why my first recommendation is to revert to the previous version of the auth-helpers (no you won't be stuck on that version as we are working on fixing the current issue). We are currently working on a way to have both fully server-side auth along with autoconfirm working too.

**Comment by skoshx** [comment] 2023-07-04 14:35
Hello @silentworks , and thanks for the thorough answer!

I understand the push towards `pkce` and that having these flows work server-side only is important especially when it seems that the industry is pushing towards that direction.

I'm glad to hear that this is something that you plan on fixing, and understand that possible changes to accomodate these fixes will take time, and I will be eagerly waiting for the fixes! :)

**Comment by i-bsd** [comment] 2023-07-05 06:18
> Got the same problem with the SignUp and the PKCE flow not supported.
> 
> Worked around that by :
> 
> * Creating the user with the supabase admin (admin key) on a serverAction
> * Then login the user on the client.
> 
> If you don't have server actions enabled, I think you could create an API route that does the same
> 
> It seems to work pretty fine.
> 
> ```ts
>     const { data } = await supbaseAdmin.auth.admin.createUser({
>       email,
>       password,
>       user_metadata: { displayName } satisfies UserMetadata,
>       email_confirm: true,
>     });
> ```

Great.

I think an API route handler might be a better way, since server actions aren't production-ready yet.

**Comment by mirsahib** [comment] 2023-07-10 03:00
I can't signup user using `createClientComponentClient` from `@supabase/auth-help-nextjs` but the default `createClient` function is working fine

**Comment by Nicolasvegam** [comment] 2023-07-10 14:34
> Hey @skoshx thanks for your detailed points here I will try and explain what happened and what we are doing to rectify this.
> 
> Firstly this isn't a marketing gimmick (i.e your statement in a previous post `(because you want it to be branded)`) this was purely an engineering oversight mainly on my part, we had this feature in pre-release for months before we decided to release it as a full release, at that point we didn't get any feedback about any of the flows not working or not being ideal, I tested out a most of these flows but only on one device/browser and also I always had email confirmation on as this is how most services I've interacted with has it setup. One of the main push for having `pkce` in all the flows was to fix our server-side story, before there was an hard requirement on the client-side in order to do signUp's and signIn's with Supabase auth, the `pkce` flow meant there was now a way to do this via the server-side only without the client being involved at all.
> 
> Rectifying this isn't as straight forward as one might think it is as we have to make some changes internally to our systems hence why my first recommendation is to revert to the previous version of the auth-helpers (no you won't be stuck on that version as we are working on fixing the current issue). We are currently working on a way to have both fully server-side auth along with autoconfirm working too.

I couldn't find that version in nextjs tho, anoyone knows?

**Comment by silentworks** [comment] 2023-07-16 10:38
We will be reverting the `autoconfirm` not supported with pkce flow as we are improving the auth flow for the SSR side of things. The new release is ready but we haven't pushed this to any project as yet since we are still testing out different use cases. 

https://github.com/supabase/gotrue/releases/tag/v2.83.0

**Comment by jkhaui** [comment] 2023-07-19 02:17
> yes exactly. why is the default method the one with highest friction?? smh bruh

PKCE should be supabase's default method as it's more secure than other auth strategies like oauth implicit flow (and not even Firebase has PKCE flow support). 

But I'm totally with you (and everyone in this discussion apparently) about the unnecessary PITA caused by further coupling the flow to email confirmation. 
I'm curious if there's a technical reason they had to be implemented together? Or is it just a suggested "best practice" thing being forced on clients

**Comment by imalexlee** [comment] 2023-07-20 18:45
Until the awesome people at supabase make a more legit fix for this, the way i currently traversed this was to roll back the @supabase/auth-helpers-nextjs version to 6.1.0. By doing this, you have to use the slightly older API. here is what to replace (at least what i replaced in my use case)

```shell
yarn remove @supabase/auth-helpers-nextjs &&
yarn add @supabase/auth-helpers-nextjs@6.1.0
``` 
### server component client
```typescript
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/dist/client/components/headers";
const supabase = createServerComponentClient({ cookies });
``` 
the above was replaced with the code below to work with version 6.1.0
```typescript
import { createServerComponentSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { cookies, headers } from "next/dist/client/components/headers";
const supabase = createServerComponentSupabaseClient({ headers, cookies });
``` 
### client/browser component client
```typescript
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";
const supabase = createClientComponentClient();
``` 
the above was replaced with the code below to work with version 6.1.0
```typescript
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";
const supabase = createBrowserSupabaseClient();
``` 

Of course, this worked in my app and might not work in yours. Hoping they issue a real fix soon!

**Comment by cuio** [comment] 2023-07-26 13:18
@michelp please help

**Comment by ramazan-umutlu** [comment] 2023-07-29 17:15
Same error ..  PKCE flow is not supported on signups with autoconfirm enabled


 "dependencies": {
        "@supabase/auth-helpers-nextjs": "^0.7.3",
        "@supabase/gotrue-js": "^2.46.1",
        "@supabase/supabase-js": "^2.31.0",
        "@types/node": "20.4.5",
        "@types/react": "18.2.17",
        "@types/react-dom": "18.2.7",
        "autoprefixer": "10.4.14",
        "next": "13.4.12",
        "npm": "^9.8.1",
        "postcss": "8.4.27",
        "react": "18.2.0",
        "react-dom": "18.2.0",
        "supabase": "^1.82.2",
        "tailwindcss": "3.3.3",
        "typescript": "5.1.6"
      }
    },


As a new js dev I shouldn't search for these errors i mean. Just trying to register user.. Should i quit?

**Comment by Surf-N-Code** [comment] 2023-07-30 11:15
> We will be reverting the `autoconfirm` not supported with pkce flow as we are improving the auth flow for the SSR side of things. The new release is ready but we haven't pushed this to any project as yet since we are still testing out different use cases.
> 
> https://github.com/supabase/gotrue/releases/tag/v2.83.0

Can we use this new tag yet and if so, how? :)

**Comment by silentworks** [comment] 2023-07-30 11:37
@Surf-N-Code that tag hasn't been deployed to any project as yet. It will get deployed in a week or so. Current deployed tag is 2.82.4.

**Comment by konstantinlindner** [comment] 2023-08-14 01:43
Any update on this? How can I enable auto-confirm without getting the PKCE error?
I'm not looking for a workaround, just basic functionality.

**Comment by faithyeenxin** [comment] 2023-08-16 02:57
@imalexlee hi, I've tried your method and it works in creating my user without email verification! Thank you! 

However I'm trying to set up a middleware to check routes whether session is available and redirect them if not.. however when I do this, session does not exist and is null. 

What is this so? 

`export async function middleware(req: NextRequest) {
  const res = NextResponse.next();
  const requestUrl = new URL(req.url);
  // Create a Supabase client configured to use cookies
  const supabase = createMiddlewareSupabaseClient({ req, res });

  // Refresh session if expired - required for Server Components
  // https://supabase.com/docs/guides/auth/auth-helpers/nextjs#managing-session-with-middleware
  const {
    data: { session },
  } = await supabase.auth.getSession();

  console.log(`middleware session: ${session}`);
  if (!session) {
    return NextResponse.redirect(requestUrl.origin);
  }
  return res;
}

export const config = {
  matcher: "/home",
};`

**Comment by caleb531** [comment] 2023-08-31 23:12
@silentworks Is there any update as to when gotrue v2.83.0 will be deployed to a project? I just ran into this error myself, and am running all the latest versions of supabase packages:

- @supabase/supabase-js 2.33.1
- @supabase/auth-helpers-nextjs 0.7.4

Any timeline you could provide would be greatly appreciated! Love the work that Supabase does.

**Comment by silentworks** [comment] 2023-09-01 17:15
@caleb531 that version should already be on your project. I just checked and we rolled out v2.92.1 some weeks ago which would include all fixes from v2.83.0. If you are on a free project try pausing/unpausing to get the latest.

**Comment by caleb531** [comment] 2023-09-01 17:40
@silentworks Well, I did confirm that the error is absent on my live Staging site's Sign Up form (running on Supabase hosting), just not in my local dev server (http://localhost:3000).

I have already tried updating the `supabase` package to the latest (v1.88.0), then running `supabase stop` and `supabase start` to download the images fresh. But I'm still getting the PKCE error locally.

<img width="465" alt="Screenshot 2023-09-01 at 10 29 17 AM" src="https://github.com/supabase/auth-helpers/assets/872474/2866a4ec-bf23-4ae6-b150-c78f0289db25">

Is there anything else I need to do to "reset" gotrue in my project? Or any special gotrue configuration I need to add to the local repository?

**Comment by silentworks** [comment] 2023-09-01 18:13
@caleb531 which version of the CLI are you currently using?

**Comment by caleb531** [comment] 2023-09-01 18:14
@silentworks Version 1.88.0:

```
$ pnpm exec supabase -v
1.88.0
```

**Comment by silentworks** [comment] 2023-09-01 18:19
@caleb531 you can create a file called `gotrue-version` inside of the `supabase/.temp` directory and add the version number you want to use in that file and it will pull the image down for you to use.

Steps to take:
- `supabase stop`
- create `gotrue-version` file inside of `supabase/.temp` directory
- Type the version number you want inside of the `gotrue-version` file `v2.92.1`
- `supabase start` and this should pull the new image

**Comment by caleb531** [comment] 2023-09-01 18:34
@silentworks So I run `supabase start`:

```
$ pnpm exec supabase stop
Postgres database saved to volume: supabase_db_faith-dashboard
Postgres config saved to volume: supabase_config_faith-dashboard
Storage directory saved to volume: supabase_storage_faith-dashboard
Stopped supabase local development setup.
```

Then I run `supabase start`, but it doesn't seem to download any new images (at it was earlier this morning):

```
$ pnpm exec supabase start
Started supabase local development setup.

         API URL: http://localhost:54321
     GraphQL URL: http://localhost:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@localhost:54322/postgres
      Studio URL: http://localhost:54323
    Inbucket URL: http://localhost:54324
      JWT secret: <secret>
        anon key: <secret>
service_role key: <secret>
```

With that, I start my local dev server again and receive the same PKCE error.

**Comment by omonk** [comment] 2023-09-01 19:40
@caleb531 good timing for me to come across this thread, i've just followed the steps above to set the gotrue-version and it has worked for me and pulling the new image and I'm no longer getting the PKCE error when creating an account

```/path/to/repo/supabase/.temp/gotrue-version```


Contents
```
v2.92.1
```

supabase start contents


```supabase start
v2.92.1: Pulling from supabase/gotrue
4060ece20d7a: Pull complete
dda6468f98aa: Pull complete
20ab543ed620: Pull complete
1c6042e25d55: Pull complete
53d6979e59b6: Pull complete```

**Comment by caleb531** [comment] 2023-09-01 19:51
@omonk Glad it worked for you!

@silentworks I just checked my Docker images, and it looks like the gotrue image is at v2.82.4, which would explain the issue for me.

So with that `gotrue-version` file already created with `v2.92.1` as the contents, I tried `supabase stop`, deleting that image, then running `supabase start` again. It still downloads v2.82.4 for some reason.

```
$ cat supabase/.temp/gotrue-version 
v2.92.1
$ supabase start
v2.82.4: Pulling from supabase/gotrue
edb6bdbacee9: Pull complete 
e66da05e113e: Pull complete 
b624d6c296c8: Pull complete 
972d4c810416: Pull complete 
e322cf576388: Pull complete 
Digest: sha256:2e4cf4e090ad0128a7e7a9fa468846c9116e000cc7bebe7a12d8acc6ad75c1be
Status: Downloaded newer image for public.ecr.aws/supabase/gotrue:v2.82.4
Started supabase local development setup.

         API URL: http://localhost:54321
     GraphQL URL: http://localhost:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@localhost:54322/postgres
      Studio URL: http://localhost:54323
    Inbucket URL: http://localhost:54324
      JWT secret: <secret>
        anon key: <secret>
service_role key: <secret>
```

**Comment by jdgamble555** [comment] 2023-09-01 21:44
@silentworks - When does this get rolled out locally for testing?

J

**Comment by caleb531** [comment] 2023-09-01 23:48
@silentworks I think I found why Supabase CLI keeps downloading the supabase/gotrue:v2.82.4 image, even after clearing pnpm store, reinstalling node modules, etc. It's because [supabase/supabase](https://github.com/supabase/supabase) (master) is still pointing to the 2.82.4 image in docker-compose.yml:

```yml
auth:
  container_name: supabase-auth
  image: supabase/gotrue:v2.82.4
```

See [~Line 89 of the docker-compose.yml file](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L89C35-L89C35).

Can someone please update this to use the latest gotrue version? Or is there a way I can manually update the image version myself?

**Comment by silentworks** [comment] 2023-09-02 02:16
@caleb531 the `supabase/supabase` repo  `docker-compose.yml` file has no relation to the CLI. You might need to change your project_id in your `supabase/config.toml` file in order for the new image to download as docker would just run your setup with the existing image it already has from previous container build. The process I have stated works as @omonk did the steps and it worked for him.

**Comment by silentworks** [comment] 2023-09-02 02:28
> @silentworks - When does this get rolled out locally for testing?
> 
> J

I stated how to get the latest using the steps above. When will this be officially set in the CLI, I'm not sure as we do take a bit longer to add stuff to the CLI than we do to the hosted platform.

**Comment by silentworks** [comment] 2023-09-02 02:29
> @silentworks I think I found why Supabase CLI keeps downloading the supabase/gotrue:v2.82.4 image, even after clearing pnpm store, reinstalling node modules, etc. It's because [supabase/supabase](https://github.com/supabase/supabase) (master) is still pointing to the 2.82.4 image in docker-compose.yml:
> 
> ```yaml
> auth:
>   container_name: supabase-auth
>   image: supabase/gotrue:v2.82.4
> ```
> 
> Source: [Line 89 of the docker-compose.yml file](https://github.com/supabase/supabase/blob/master/docker/docker-compose.yml#L89C35-L89C35).
> 
> I also found another reference to v2.82.4 in [supabase-cli](https://github.com/supabase/cli): https://github.com/supabase/cli/blob/main/internal/utils/misc.go#L41
> 
> Can someone please update these places to use the latest supabase/gotrue image? Or is there a way I can manually update the image versions myself?

@caleb531 to update it yourself would be the steps I provided you with earlier.

**Comment by Tolluset** [comment] 2023-09-02 20:14
> @caleb531 you can create a file called `gotrue-version` inside of the `supabase/.temp` directory and add the version number you want to use in that file and it will pull the image down for you to use.
> 
> Steps to take:
> 
> * `supabase stop`
> * create `gotrue-version` file inside of `supabase/.temp` directory
> * Type the version number you want inside of the `gotrue-version` file `v2.92.1`
> * `supabase start` and this should pull the new image

After downloading new images, signup worked. Thanks!

**Comment by jdgamble555** [comment] 2023-09-02 23:31
> I stated how to get the latest using the steps above. When will this be officially set in the CLI, I'm not sure as we do take a bit longer to add stuff to the CLI than we do to the hosted platform.

@silentworks - I think you should move this up the ladder as a problem (the fact that it takes longer to add stuff to CLI).  People develop before they update their production versions, if anything this is backwards.  I keep reading everywhere that Supabase tries to have the local version match the hosted platform, yet huge issues like this continue to create problems for people.  Hence, why we see many complaints about developing on local.

That being said, I appreciate you and the work around.

J

**Comment by silentworks** [comment] 2023-09-03 01:19
@jdgamble555 we started as a hosted first solution, there was no CLI until like around a year ago. Most of our users use the hosted first approach too but this is something we have started putting effort into fixing (we still have users whose machines cannot handle Docker as its resource heavy). From the outside everything might look like a quick and easy PR but thats not how all the moving parts of Supabase work. I come from a background of local development first approach as this is how it was with PHP, but you need to remember that Supabase isn't a language or a framework, its an amalgamation of different open source technologies being provided to an user, this is something thats not easy to deliver for local development.

**Comment by DOZBORNE** [comment] 2023-09-03 04:47
> @caleb531 you can create a file called `gotrue-version` inside of the `supabase/.temp` directory and add the version number you want to use in that file and it will pull the image down for you to use.
> 
> Steps to take:
> 
> * `supabase stop`
> * create `gotrue-version` file inside of `supabase/.temp` directory
> * Type the version number you want inside of the `gotrue-version` file `v2.92.1`
> * `supabase start` and this should pull the new image

Just found this! Works! 

Yeah, if it didn't pull images, just a docker issue. Similar to when using `docker compose`, you may have to "force" pull images using `docker compose pull`, which will force fetch latest images. Same thing in this case, just ensure that the image pulls. 

Thanks for your time @silentworks !

**Comment by silentworks** [comment] 2023-09-04 00:43
I'm closing this out as it has been resolved on hosted Supabase and can be resolved in local Supabase following the instructions I've left on this issue.

**Closed by silentworks** 2023-09-04 00:43 UTC
Labels: bug

**Comment by piccinnigius** [comment] 2023-09-04 09:58
Hi @silentworks when creating the file i got this:

```npx supabase start      
invalid reference formatema...
                        Retrying after 4s: public.ecr.aws/supabase/gotrue:v2.95.0

invalid reference formatema...
                        Retrying after 8s: public.ecr.aws/supabase/gotrue:v2.95.0

invalid reference format
```

any hint?

**Comment by silentworks** [comment] 2023-09-04 13:10
@piccinnigius it is adviced to not use a version locally that hasn't been deployed to the platform as yet. The current version that has been deployed to the platform is v2.92.1.

**Comment by piccinnigius** [comment] 2023-09-04 13:12
@silentworks ok thanks so much for the advice 🙏

**Comment by jdgamble555** [comment] 2023-09-04 16:15
@silentworks - A suggestion about closing threads. There are developer and user reasons to not close an issue until it is actually fixed, not with a work-around, which is what this is.  Anyone who is using the latest local version of Supabase and trying to test an auth flow could come across this error and need to read this Github issue.  Not only is your fix in the middle of this thread and hard to find, it will be under closed issues.  It might be advantageous to keep this open for those people until the CLI update is pushed.

That being said, on a different note, I was getting this error when using the fix with `supabase db reset`:

When I use the "v2.92.1," I am getting the:
> "Failed to load configuration: required key API_EXTERNAL_URL missing value"

Which is said to be fixed in the latest cli version: https://github.com/supabase/supabase/issues/16702

However, I can't use the latest CLI version, or I will not have this issue fixed.  Perhaps I a missing something here.

Thanks,

J

**Comment by silentworks** [comment] 2023-09-04 18:19
@jdgamble555 any reason why you can't use the latest CLI version? btw the issue you are having now isn't related to this thread, probably best to move it over to the CLI repo and tag me there.

You might be confusing what issue this thread is about when you say it hasn't been fixed. The original author of this issue said this wasn't working in self-hosted (not CLI) but this has been fixed in both hosted and self-hosted (since this is up to a user to manage and they can simply pull the docker container for the gotrue version with the fix mentioned).

The fix for anyone using the CLI is stated above in this comment https://github.com/supabase/auth-helpers/issues/569#issuecomment-1703159422

**Comment by jdgamble555** [comment] 2023-09-04 20:45
@silentworks - Well you need the CLI to install the docker, but this is a moot point now.  Got it working by deleting all docker files and reinstalling (with the gotrue-version file intact).

Thanks for you help :)

My other point was just to not close this until the gotrue version is pushed as the default version on docker for the reasons I mentioned above.

J

**Comment by jeremypeters** [comment] 2023-09-14 19:44
I've just hit the same issue as @jdgamble555. I've had to add v2.92.1 to the `gotrue-version` as the recommended workaround to prevent the PKCE error, but now I am also experiencing the same "Failed to load configuration: required key API_EXTERNAL_URL missing value" error using this version.

**Comment by raulghm** [comment] 2023-09-21 01:41
Upgrading supabase package to last version resolve the issue en my case.

**Comment by jdgamble555** [comment] 2023-09-23 16:29
The latest cli version seems to have updated gotrue, so you don't need the [workaround](https://github.com/supabase/auth-helpers/issues/569#issuecomment-1703159422) anymore.

J

**Comment by rdewolff** [comment] 2023-11-04 16:24
I can confirm that updating my local supabase instance has fixed the issue 🕺🎉

Simply `stop` and `start` the supabase instance, it has downloaded the last version and works. 

```
supabase stop
supabase start
```

Thanks for everyone that took the time to investigate the issue and help solve it :)

**Comment by azer** [comment] 2024-05-13 15:34
In a fresh installation (with `npx create-next-app -e with-supabase`) I'm getting the PKCE flow error for sign ups. I hope Supabase addresses this issue soon -- it's unfortunate to have such an issue in fresh installation path.
