### ISSUE TITLE
 @supabase/ssr supabase.auth.getSession() returns valid session for deleted user

### ISSUE THREAD

**Issue by kvetoslavnovak** [supabase/auth-helpers#702] opened 2023-12-09 09:44 UTC
# Bug report
- &#x2611;  I confirm this is a bug with Supabase, not with my own application. 
- &#x2611;  I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Testing new @supabase/ssr with SvelteKit. Using the official docs example. It seems to me there is no ongoing cookie check. If I have a runnig SvelteKit applicaton with logged in user and delete the user in Supabase  then the user can happiliy use the application and cookie validity seems not to be checked. 

Simply speaking  `supabase.auth.getSession()` gives a valid session even if  the user was deleted in a database.

According  to the documentation for ScelteKit there is  depends('supabase:auth')  in +layout.ts. I guess this was ment to prevent the issue. But I do not see where and when invalidate('supabase:auth') is called. The auth-helpers used to use this with the cookie expiration check within supabase.auth.onAuthStateChange() in +layout.svelte

## To Reproduce
Use any Supabase exaple app with logged in user. Delete the user in the database. You will be able to use the app in the frontend happily or call  `supabase.auth.getSession()` and get valid session. Untill teh user loggs out  or hard refreshes the app. 

As per official docs https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=hooks

My detail implementation in SvelteKit is here https://dev.to/kvetoslavnovak/supabase-ssr-auth-48j4

## Expected behavior
`supabase.auth.getSession()` should ckech wehter the user still exists. and the cookie validaty should be ckecked everytime the user accesses the backend.

## System information
- SvelteKit 4, Vercel

**Comment by kvetoslavnovak** [comment] 2023-12-09 22:12
I have tested this isssue a little bit more.. It seems  the problem is that supabase.auth.getSession()  returns session for user even if the user was deleted from the Supaase database, If there is still a user in a browser (the user did not logged out, there is stilll user cooke in a browser) the user can acces  the database still. 
So it seems that the supabase.auth.getSession()  does not have the check whether  the user still exists in a database. This might seem quite dangerous.

**Comment by kvetoslavnovak** [comment] 2023-12-11 13:18
Here is a workarround that can be use in SvelteKit.

Referrring to the docymentation https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=hooks

```js
// hooks.server.js
import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY } from '$env/static/public'
import { createServerClient } from '@supabase/ssr'
import addUserprofileToUser from './utils/addUserprofileToUser'

export const handle = async ({ event, resolve }) => {
  event.locals.supabase = createServerClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
    cookies: {
      get: (key) => event.cookies.get(key),
      set: (key, value, options) => {
        event.cookies.set(key, value, options)
      },
      remove: (key, options) => {
        event.cookies.delete(key, options)
      },
    },
  })

  /**
   * a little helper that is written for convenience so that instead
   * of calling `const { data: { session } } = await supabase.auth.getSession()`
   * you just call this `await getSession()`
   */
  event.locals.getSession = async () => {
    let {
      data: { session },
    } = await event.locals.supabase.auth.getSession()
    // the session.user gets overwritten back again in layout according to the cookie and will lost user_profile
    // so this function will be repeted in layout server files again
    // having this in hooks just to be consistent and sure
    await addUserprofileToUser(session,event.locals.supabase)

    const { data: getUserData, error: err }  = await event.locals.supabase.auth.getUser()

    if (getUserData.user == null) {
      session = null
    }
    
    return session
  }

   return resolve(event, {
    filterSerializedResponseHeaders(name) {
      return name === 'content-range'
    },
  })
}
```

```js
// +layout.server.js
import addUserprofileToUser from '../utils/addUserprofileToUser.js'
export const load = async (event) => {

let session = await event.locals.getSession()

if (!session) {
  event.cookies.delete(event.locals.supabase.storageKey);
}

await addUserprofileToUser(session, event.locals.supabase)
  return {
    session
  }
}
```

**Comment by thorleifjacobsen** [comment] 2023-12-17 22:45
I've jsut met this aswell, but getSeesion checks the local session storage for a JWT and it is supposed to be valid. It will fail any requests as long as the user is deleted. So is this a bug? And could there bet a better workaround to "really verify" on reload? :)

**Comment by internpoon** [comment] 2023-12-18 07:09
+1, the migration guide from the old sveltekit auth helper to ssr is not complete :( any chance to update the guide ?

**Comment by silentworks** [comment] 2023-12-20 04:22
Yes `getSession` will use the JWT it has in storage. However a user cannot request new data if that JWT has expired. You should set your JWT to be short lived so that a refresh happens often enough to refresh the JWT each time and see if the user still exists. You can also use `getUser` but this is down to you to determine which is the best option to go by. It's on a per application basis and not a one size fits all.

**Comment by kangmingtay** [comment] 2023-12-20 23:36
yup @silentworks is right, to add on, this is a property of JWTs - they cannot be revoked immediately and will continue to provide access to the application until it's being expired. 

When you delete the user from the database, your client application has no idea that the user has been deleted. The jwt will continue to work but it probably won't be useful if your application relies on the user's ID as a foreign key elsewhere, since any queries made to the db with that user's ID will return 0 rows. 

We've also mentioned this in the docs that [`getSession()`](https://supabase.com/docs/reference/javascript/auth-getsession) returns the local session.

**Comment by eurlexa** [comment] 2023-12-21 22:09
Yes, I geuss this is not a bug per se. Just the develoopers should be carefull and aware fo this May to add to the documentation that  getSession() runs only client side checking just the local session.

**Comment by kvetoslavnovak** [comment] 2023-12-21 22:10
Yes, I geuss this is no bug per se. Just the develoopers should be carefull and aware fo this May to add to the documentation that getSession() runs only client side checking just the local session.

**Comment by thorleifjacobsen** [comment] 2023-12-22 00:25
But it says in the documentation that it refreshes if the token is expired so it is not only client side check. :)

**Comment by kangmingtay** [comment] 2023-12-22 04:00
@thorleifjacobsen yes, but the token is still valid until it's expired. when it is expired, the auth service will throw an error as it attempts to refresh the session but notices that the user has been deleted

**Comment by dijonmusters** [comment] 2024-01-17 10:55
Closing as this is expected behaviour 👍

**Closed by dijonmusters** 2024-01-17 10:55 UTC
