### ISSUE TITLE
Remix example does not work

### ISSUE THREAD

**Issue by fred-transitiv** [supabase/auth-helpers#483] opened 2023-04-03 03:45 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The remix auth helper example does not "work." Cloning this repo then navigating to the folder and running "npm run dev" results in "PORT is not recognized." npm build also fails, because auth-helpers is referencing workspace:*. 

This would be fine if the README didn't claim all you had to do was copy the code down and run npm run dev.

Once you fix these issues however (I removed the PORT commands and referenced the latest auth-helper from npm), the app still doesn't "work."

Pressing the login or logout button results in nothing happening in the front end. And if you try to click another link afterward or refresh the page, the browser tab crashes. There are no errors logged. If you close the page and open a new tab and navigate to the same local url, you'll find the auth state changed predictably.

This seems to be a bug with how useEffect is being used. It's not accomplishing the goal of syncing the client and server and is in fact causing a fatal error when you try and refresh. If you simply comment this code out, predictably, you can at least refresh the page to update your state.

Generally the Supabase Remix Auth scene is a nightmare. I've followed tutorials for NextJS and Supabase and the examples are far easier to follow and the final result is -- it works. In comparison there are about 6 different ways to do supabase auth in Remix (according to online tutorials) and most of them don't work. This is the only method I've found that almost works with the latest libraries from Supabase and Remix but it still isn't fully functional.

## To Reproduce

1. Remove the PORT part of the remix commands from package.json
2. Replace the workspace:* line in package.json with "@supabase/auth-helpers-remix": "^0.1.5",
3. Update .env.local to .env and add your key/url
4. Change the username/password for email sign in on login.tsx
5. npm run dev
6. navigate to localhost:3000
7. click sign in.
8. Try clicking a link or refreshing the page

## Expected behavior

I would expect clicking login to log me in and re-render the page with the logout button and visa versa.

## System information

- OS: [Windows]
- Browser (if applies) [chrome, edge]
- Version of supabase-js: this library doesn't use it, it uses the wrapper auth-helpers-remix
- Version of Node.js: [e.g. 16.7.1]

**Comment by fred-transitiv** [comment] 2023-04-03 03:51
I added some console logs after submitting this and the useEffect is somehow getting called in an infinite loop, hence the crashing.

**Comment by fred-transitiv** [comment] 2023-04-03 04:24
The issue is passing fetcher as an argument to useEffect. Not sure what the intention was there. Guess I'm still interested in hearing why that was done or why I'd need to pass serverToken AND supabase -- presumably I only care about serverToken changing.

**Comment by silentworks** [comment] 2023-04-05 11:48
This is not how this repo works, this repo is for development of the auth-helpers. The examples are purely for the use in developing the auth-helpers and shouldn't be used outside of this repo. You should create your own project using the published `@supabase/auth-helpers-remix` and not try to use the examples here as a starting point for your project, this is a monorepo and all examples are intended to work only in the monorepo.

**Comment by fred-transitiv** [comment] 2023-04-05 13:07
I understand that. I'm not literally using it as a remix stack/starter. The example is absolutely being used as a template for developers to look at and "reusue."

It's linked here:

https://supabase.com/docs/guides/auth/auth-helpers/remix

And on John's Egghead course.

It's also titled "example" with a readme.

I ran it locally to make sure I wasn't crazy when I noticed this bug in my own project following John's tutorials.

Thanks.

**Comment by silentworks** [comment] 2023-04-05 14:23
I'm going to ask Jon to create a separate example repo for the course as this one isn't suited for that use case. In a monorepo settings you don't install dependencies in the example folder itself, we are using `pnpm` and you would run `pnpm install` from the root level of the project and also run `pnpm dev --filter=@example/remix` from the same root level to view the dev environment of the project. Here I've attached a video with this working in the monorepo, all I did was add my env variables and change the sign in email/password and then run the project.

https://user-images.githubusercontent.com/79497/230110553-bbd51d06-cb2b-4dca-9034-9e094bd0e071.mp4

**Comment by jbsmith731** [comment] 2023-04-05 14:26
Hi @silentworks I can confirm the app does initially run as is. The problem I've seen is over time it will crash due to the issue stated by @fred-transitiv

**Comment by jbsmith731** [comment] 2023-04-05 14:36
I'm not sure the exact pattern/steps to replicate but I've had it crash multiple times in both dev/production mode. Trying to work on a more solid reproduction.

**Comment by silentworks** [comment] 2023-04-05 14:37
I'm closing this one out until a solid reproduction can be produced.

**Closed by silentworks** 2023-04-05 14:37 UTC
Labels: bug

**Comment by fred-transitiv** [comment] 2023-04-05 15:01
@silentworks 

As I said in my first comment the issue is quite easy to reproduce.

Simply try to login or logout. Doing so triggers an update to the auth subscription. Which calls fetcher. Which triggers an update to fetcher. Which triggers an update to the auth subscription. Etc.

All you have to do is remove fetcher from the array args in the useEffect.

**Comment by fred-transitiv** [comment] 2023-04-05 15:02
Working code: 

```
  useEffect(() => {
    const {
      data: { subscription }
    } = supabase.auth.onAuthStateChange((event, session) => {
      if (session?.access_token !== serverAccessToken) {
        // server and client are out of sync.
        // Remix recalls active loaders after actions complete
        fetcher.submit(null, {
          method: 'post',
          action: '/handle-supabase-auth'
        });
      }
    });

    return () => {
      subscription.unsubscribe();
    };
  }, [serverAccessToken, supabase]);
```
