### ISSUE TITLE
Logging in with multiple social providers (same email) does not always work

### ISSUE THREAD

**Issue by dsebastien** [supabase/auth-helpers#574] opened 2023-06-01 08:24 UTC
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
When an account has been created using one provider (e.g., email, Google, etc) and the user tries to log in using another, it doesn't always work. For example, see the scenario below.

## To Reproduce

Create an account with username/password (email provider)
Sign out
Sign in with Google --> Should work, and the account should now have two providers (email + google)
Sign out
Sign in with GitHub --> should fail with "Multiple accounts with the same email address in the same linking domain detected" and the user should not be logged in

## Expected behavior

No error and the user should be logged in. Also, the user should have three providers then: email + google + github
## System information

- Version of @supabase/supabase-js: 2.24.0
- Version of @supabase/auth-helpers-nextjs: 0.6.1
- Version of @supabase/auth-helpers-react: 0.3.1
- Version of supabase: 1.66.0
- Version of Node.js: 16.20.0

**Comment by hazelnutcloud** [comment] 2023-06-13 06:45
I ran into this issue and after some investigating, I can conclude that this happens when the github account has multiple emails linked to it and those emails already exist as separate accounts in the supabase auth table

**Comment by mercicle** [comment] 2023-07-10 19:31
+1 same error for the reason @hazelnutcloud described.

**Comment by kangmingtay** [comment] 2023-08-07 04:42
Hey @dsebastien, @hazelnutcloud and @mercicle,

This only happens if you have 2 identities with the same email address linked to 2 different users - which can happen in the following scenario:
User A signs in with google using `user@foo.com` 
User B signs in with facebook using `user@bar.com`
User B changes facebook email from `user@bar.com`
User C tries to sign in with twitter using `user@foo.com`
When user C tries to login in (4), the twitter identity is detected as a new identity and gotrue tries to automatically link it by email. But because there are 2 identities with the same email (google & facebook with `user@foo.com` that point to different users, we can't tell if the twitter identity should be linked to either one of them.

Currently, the only workaround is to manually resolve these conflicts by checking if there are 2 identities with the same `auth.identities.email` that link to 2 different `auth.users`.

You can run the following query to check which accounts are violating:

```sql
select email, array_agg(distinct user_id) 
from auth.identities 
group by email 
having array_length(array_agg(distinct user_id), 1) > 1;
```

**Comment by silentworks** [comment] 2023-09-04 14:20
Closing this as a workaround was provided by @kangmingtay and this is also not an issue with the library but the underlying Gotrue implementation.

**Closed by silentworks** 2023-09-04 14:20 UTC
Labels: bug

**Comment by hexcowboy** [comment] 2023-09-04 21:33
> This only happens if you have 2 identities with the same email address linked to 2 different users - which can happen in the following scenario:

Actually, we are able to reproduce this when a user signs in using OTP and then proceeds to create an account with Github.

**Comment by hexcowboy** [comment] 2023-09-05 18:08
> hmm could you outline the steps you took? this might have happened because the new github account created uses the same email address as another identity linked to a different account

this is exactly the case
1. `foo@bar.com` signs in with OTP
2. `foo@bar.com` sign in with Github oauth - this is where the error occurs

however, our application logic does not depend on these two accounts being linked. they could be completely separate accounts.

**Comment by kangmingtay** [comment] 2023-09-05 18:14
@hexcowboy thanks! it would be great if you can reach out to us via support (https://supabase.com/dashboard/support/new) so that we can investigate the issue with your project

**Comment by eposha** [comment] 2023-11-26 02:41
@kangmingtay Any suggestions on how to solve this issues?

**Comment by Bryce-Stabenow** [comment] 2023-12-31 02:34
I can also confirm that I'm experiencing this behavior. I have signed in with Gitlab on my application, and then used Google as well (both have the same primary email). Both users are able to see and retrieve the same data, despite different login methods, which seems problematic

**Comment by J0** [comment] 2024-01-05 14:11
Hey @Bryce-Stabenow,

Thanks for reporting the issue.  This is expected behaviour - Supabase Auth will automatically link the Gitlab account with the Google account if they both have the same primary email.  There's a new set of identity primitives which allow you to unlink two identities or manually link to a separate identity. You can read more about it [here](https://supabase.com/docs/guides/auth/auth-identity-linking)

Hope this helps and let us know if there are still further issues
